services:
  database:
    image: postgres:trixie@sha256:ad98a3ba6a3b5e53e9bd95afed6930d3103efc890240643a168b590bcf2e6e81
    environment:
      POSTGRES_DB: seekretsanta
      POSTGRES_USER: seekretsanta_user
      POSTGRES_PASSWORD: seekretsanta_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - seekretsanta-network
  backend:
    image: pozniako/seekretsanta-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILE_ACTIVE: docker
    depends_on:
      - database
    networks:
      - seekretsanta-network
  frontend:
    image: pozniako/seekretsanta-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - seekretsanta-network
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080

  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
    networks:
      - seekretsanta-network
    ports:
      - "80:80"
      # Uncomment 443 after placing certs
      # - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro

volumes:
  postgres_data:

networks:
  seekretsanta-network:
    driver: bridge
