name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend-validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Validate package-lock.json is up to date
        run:
          npx --yes package-lock-utd@1.x.x
  frontend:
    needs: frontend-validation
    uses: poznit/workflows/.github/workflows/template-build-release.yml@main
    with:
      working-directory: ./frontend
      app-name: seekretsanta-frontend
      runner: ubuntu-24.04
    secrets: inherit

  backend:
    needs: frontend-validation
    uses: poznit/workflows/.github/workflows/template-build-release.yml@main
    with:
      working-directory: ./backend
      app-name: seekretsanta-backend
      runner: ubuntu-24.04
    secrets: inherit

  prepare_deploy:
    needs: [ frontend, backend ]
    uses: poznit/workflows/.github/workflows/template-rsync-dir.yml@main
    with:
      source_folder: nginx
      target_folder: .deploy/${{ github.event.repository.name }}/nginx
    secrets: inherit
  deploy:
    needs: [ prepare_deploy ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare deployment
        uses: poznit/workflows/.github/actions/prepare-deploy@main
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.SSH_USER }}

      - name: Create override file
        run: |
          cat > docker-compose.override.yml << EOL
          services:
            backend:
              image: ${{ secrets.DOCKERHUB_USER }}/seekretsanta-backend:${{ github.sha }}
            frontend:
              image: ${{ secrets.DOCKERHUB_USER }}/seekretsanta-frontend:${{ github.sha }}
          EOL
      - name: deploy
        uses: poznit/workflows/.github/actions/deploy@main
        with:
          compose_file: docker-compose.yml
          compose_override_file: docker-compose.override.yml
          deployment_folder: "~/.deploy"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.SSH_USER }}
