name: Artifacts purge

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  purge:
    uses: poznit/workflows/.github/workflows/purge-artifacts.yml@main
    with:
      repository: ${{ github.repository }}
      personal_github_token: ${{ secrets.ARTIFACT_PURGE_TOKEN }}
