name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend-validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Validate package-lock.json is up to date
        run:
          npx --yes package-lock-utd@1.x.x
  frontend:
    needs: frontend-validation
    uses: ./.github/workflows/build-release-template.yml
    with:
      working-directory: ./frontend
      app-name: seekretsanta-frontend
      runner: ubuntu-24.04
    secrets: inherit

  backend:
    needs: frontend-validation
    uses: ./.github/workflows/build-release-template.yml
    with:
      working-directory: ./backend
      app-name: seekretsanta-backend
      runner: ubuntu-24.04
    secrets: inherit

  deploy:
    needs: [ frontend, backend ]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: humbertocrispim/ssh-docker-compose-action@v1.0.0
          name: Deploy with Docker Compose
          with:
            ssh_host: ${{ secrets.SSH_HOST }}
            ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
            ssh_user: ${{ secrets.SSH_USER }}
            docker_compose_prefix: myapp
            pull: true
