name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend-validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Validate package-lock.json is up to date
        run:
          npx --yes package-lock-utd@1.x.x
  frontend:
    needs: frontend-validation
    uses: ./.github/workflows/build-release-template.yml
    with:
      working-directory: ./frontend
      app-name: seekretsanta-frontend
      release-tag: ${{ github.sha }}
      runner: ubuntu-24.04

  backend:
    uses: ./.github/workflows/build-release-template.yml
    with:
      working-directory: ./backend
      app-name: seekretsanta-backend
      release-tag: ${{ github.sha }}
      runner: ubuntu-24.04
