name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    inputs:
      frontend_app:
        description: name of the frontend app
        required: false
        type: string
        default: seekretsanta-frontend
      backend_app:
        description: name of the backend app
        required: false
        type: string
        default: seekretsanta-backend
      compose_file:
        description: name of the docker-compose file
        required: false
        type: string
        default: docker-compose-prod.yml
      compose_override_file:
        description: name of the docker-compose override file
        required: false
        type: string
        default: docker-compose.override.yml

jobs:
  frontend-validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Validate package-lock.json is up to date
        run:
          npx --yes package-lock-utd@1.x.x
  frontend:
    needs: frontend-validation
    uses: ./.github/workflows/build-release-template.yml
    with:
      working-directory: ./frontend
      app-name: ${{ inputs.frontend_app }}
      runner: ubuntu-24.04
    secrets: inherit

  backend:
    needs: frontend-validation
    uses: ./.github/workflows/build-release-template.yml
    with:
      working-directory: ./backend
      app-name: ${{ inputs.backend_app }}
      runner: ubuntu-24.04
    secrets: inherit

  prepare-deploy:
    needs: [ frontend, backend ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List images
        run: |
          echo "Frontend image: ${{ secrets.DOCKERHUB_USER }}/${{ inputs.frontend_app }}:${{ github.sha }}"
          echo "Backend image: ${{ secrets.DOCKERHUB_USER }}/${{ inputs.backend_app }}:${{ github.sha }}"

      - name: Create compose overrides
        run: |
          cat > ${{ inputs.compose_override_file }} << EOL
          services:
            backend:
              image: ${{ secrets.DOCKERHUB_USER }}/${{ inputs.backend_app }}:${{ github.sha }}
            frontend:
              image: ${{ secrets.DOCKERHUB_USER }}/${{ inputs.frontend_app }}:${{ github.sha }}
          EOL
      - name: Store in artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.compose_override_file }}
          path: ${{ inputs.compose_override_file }}

  deploy:
    needs: prepare-deploy
    uses: ./.github/workflows/deploy-template.yml
    with:
      compose_file: ${{ inputs.compose_file }}
      compose_override_file: ${{ inputs.compose_override_file }}
      deployment_folder: .deploy
    secrets: inherit
