name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend:
    uses: ./.github/workflows/build-release-template.yml
    with:
      working-directory: ./frontend
      app-name: seekretsanta-frontend
      release-tag: ${{ github.sha }}
      runner: ubuntu-24.04
  backend:
    uses: ./.github/workflows/build-release-template.yml
    with:
      working-directory: ./backend
      app-name: seekretsanta-backend
      release-tag: ${{ github.sha }}
      runner: ubuntu-24.04
