name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FRONTEND_APP: seekretsanta-frontend
  BACKEND_APP: seekretsanta-backend
  COMPOSE_FILE: docker-compose-prod.yml
  OVERRIDE_FILE: docker-compose.override.yml

jobs:
  frontend-validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Validate package-lock.json is up to date
        run:
          npx --yes package-lock-utd@1.x.x
  frontend:
    needs: frontend-validation
    uses: ./.github/workflows/build-release-template.yml
    with:
      working-directory: ./frontend
      app-name: ${{ env.FRONTEND_APP }}
      runner: ubuntu-24.04
    secrets: inherit

  backend:
    needs: frontend-validation
    uses: ./.github/workflows/build-release-template.yml
    with:
      working-directory: ./backend
      app-name: ${{ env.BACKEND_APP }}
      runner: ubuntu-24.04
    secrets: inherit

  deploy:
    needs: [ frontend, backend ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ env.COMPOSE_FILE }}
          target: "~/.deploy/${{ github.event.repository.name }}/"

      - name: Create docker-compose.override.yml on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat > ~/.deploy/${{ github.event.repository.name }}/${{ env.OVERRIDE_FILE }} <<EOL
            services:
              backend:
                image: ${{ secrets.DOCKERHUB_USER }}/${{ env.BACKEND_APP }}:${{ github.sha }}
              frontend:
                image: ${{ secrets.DOCKERHUB_USER }}/${{ env.FRONTEND_APP }}:${{ github.sha }}
            EOL

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/.deploy/${{ github.event.repository.name }}
            docker compose -f ${{ env.COMPOSE_FILE }} -f ${{ env.OVERRIDE_FILE }} stop
            docker compose -f ${{ env.COMPOSE_FILE }} -f ${{ env.OVERRIDE_FILE }} rm -f
            docker compose -f ${{ env.COMPOSE_FILE }} -f ${{ env.OVERRIDE_FILE }} pull
            docker compose -f ${{ env.COMPOSE_FILE }} -f ${{ env.OVERRIDE_FILE }} up -d
            docker image prune -af
