name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  #frontend:
  #  runs-on: ubuntu-24.04
  #  steps:
  #    - uses: actions/checkout@v4
  #    - name: Build docker
  #      run: |
  #        cd frontend
  #        docker build . --file Dockerfile --tag seekretsanta-frontend:$(date +%s)
  backend:
    uses: ./github/workflows/build-release-template.yml
    with:
      working-directory: ./backend
      app-name: seekretsanta-backend
      release-tag: ${{ github.sha }}
