name: Scp directory
on:
  workflow_call:
    inputs:
      source_folder:
        description: source_folder
        required: true
        type: string
      target_folder:
        description: target_folder
        required: true
        type: string

jobs:
  scp-directory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Copy folder
        run: scp -r ${{ inputs.source_folder }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/${{ inputs.target_folder }}/

      - name: Fix permissions
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "chmod -R 755 ~/${{ inputs.target_folder }}"
